POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{ 
  "name": "Ada", 
  "number": "39-44-5323523"
}

###
GET https://phonebook-backend-k36c.onrender.com/api/persons/

###
GET http://localhost:3001/info/ HTTP/1.1